server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/flight_booking_project?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    password: 1234
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: "qquanquann6996@gmail.com"
    password: "zsthumjhjxwpflxk"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jackson:
    time-zone: UTC
jwt:
  private-key: +GG6Ogmkz1CD6OpczBSwP8VhyjU+7uXaYeXcQyz2zlU=